### ISSUE TITLE
missing tests

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#417] opened 2016-11-12 04:44 UTC
- [ ] TRR and XTC formats
- [x] Action_Dipole - Its test is actually in `test/Test_Grid/`
- [x] Action_Channel - **updated** I see this Action is hidden. So never mind. :D 

(will update more)

**Comment by drroe** [comment] 2016-11-17 20:23
>  Action_Dipole - Its test is actually in test/Test_Grid/

This command is pretty much obsolete; it writes out in a format that is only readable by a plugin for the now-defunct MIDAS program. It's possible that the functionality has survived in chimera somewhere but I'm not sure. Bottom line is that I think it's fine to have it's regression test mixed in with `grid` since they share a good amount of code between them.

**Comment by drroe** [comment] 2016-12-29 16:21
Addressed by #446

**Closed by drroe** 2016-12-29 16:21 UTC
