### ISSUE TITLE
macos issue - ld: library not found for -lgfortran

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#585] opened 2018-02-26 04:10 UTC
Hi,

pytraj has been using 
```
bash configure -shared -macAccelerate -noarpack   -nosanderlib  CXX="clang++ -stdlib=libstdc++"
```

but getting the above error recently.

Below command is just fine.
```
bash configure -shared -macAccelerate clang
```

**Comment by drroe** [comment] 2018-02-26 13:30
Does `./configure -shared -macAccelerate -noarpack -nosanderlib clang` work? You shouldn't need to sneak flags in via the CXX variable (at least not anymore).

The error message occurs because you are using the built-in FFT library (pubfft) which is written in Fortran, hence the need for the C++/Fortran link (`-lgfortran`), but Fortran libraries do not appear to be available on your system. Using `-noarpack` and specifying an external FFTW3 library will get rid of the Fortran dependency.

**Comment by hainm** [comment] 2018-02-26 15:18
> Does ./configure -shared -macAccelerate -noarpack -nosanderlib clang work? 

yeap.

>  but Fortran libraries do not appear to be available on your system. 

I think I have fotran libraries (If not, how specifying "clang" above works).

> You shouldn't need to sneak flags in via the CXX variable (at least not anymore).

How can I add "-stdlib=libstdc++"?

**Comment by hainm** [comment] 2018-02-26 15:19
(this is stand for standalone pytraj).

**Comment by drroe** [comment] 2018-03-08 18:36
@hainm Is this still an issue after #589?

**Comment by hainm** [comment] 2018-03-08 18:47
Hi, I will check this tonight.

**Comment by hainm** [comment] 2018-03-08 23:59
unfortunately this is still an issue. Below is exact command that works before.

```
bash configure -shared -macAccelerate -noarpack  -nosanderlib  \
     CXX="clang++ -stdlib=libstdc++"
```

**Comment by drroe** [comment] 2018-03-13 13:35
I can't reproduce this issue, so I think we will need to work a little closer to resolve this. You stated that
```
./configure -shared -macAccelerate -noarpack -nosanderlib clang
```
works, so can't you just use that?

**Comment by hainm** [comment] 2018-03-13 16:38
Do you mean cpptraj won't respect CXX and CC envs anymore? I need you to confirm those things before fixing things in pytraj.

The compilation is a bit complicated since pytraj have both standalone and ambertools versions, I don't want to mess it up before releasing AT.

**Comment by drroe** [comment] 2018-03-13 18:15
I finally figured it out. Sorry it took so long.

> Do you mean cpptraj won't respect CXX and CC envs anymore?

No, CPPTRAJ still respects CXX etc. environment variables. The issue is in how configure determines whether Fortran libraries are required for linking. I incorrectly assumed that the bundled PubFFT required the Fortran cross-linking flags, but that is not the case. If you were to specify FFTW instead, I bet this error goes away.

I'm testing a fix now and will let you know when it is live.

PS - You may want to have the option of using FFTW with pytraj instead of bundled PubFFT one day. The new PME stuff in cpptraj currently requires it.

**Comment by hainm** [comment] 2018-03-13 18:26
Thanks

Per PME stuff, does cpptraj need libsander? (libcpptraj does not link with
that intentionally).

**Comment by drroe** [comment] 2018-03-13 19:02
> Per PME stuff, does cpptraj need libsander? (libcpptraj does not link with
that intentionally).

No - the PME stuff in cpptraj is completely separate from Amber. It (specifically the reciprocal energy) is provided via the PME library being written by Andy Simmonett. It requires C++11 and FFTW (C++11 support is what eventually led me to rewrite the CPPTRAJ configure script).

**Comment by drroe** [comment] 2018-03-13 19:03
Should be fixed by #591.

**Comment by hainm** [comment] 2018-03-13 22:59
thanks. Works as normal now.

**Comment by hainm** [comment] 2018-03-15 03:32
uhm, I am getting linking error with linux build (macos build is fine)

```
libcpptraj.so: undefined symbol: _gfortran_transfer_integer_write
```

Log is here (search for "CPPTRAJ configuration complete.")
[pytraj_log.txt](https://github.com/Amber-MD/cpptraj/files/1813909/pytraj_log.txt)

**Comment by drroe** [comment] 2018-03-16 12:51
I'm having trouble getting pytraj to work - I'm sure it's something weird I'm doing. I installed pytraj using
```
python setup.py install --user
```
My PYTHONPATH is set.
```
$ ls $PYTHONPATH
easy-install.pth  ParmEd-2.7.1-py2.7-linux-x86_64.egg  pytraj-2.0.3.dev0-py2.7-linux-x86_64.egg
```
When I try to import pytraj I get an error that there is no module named `topology_objects`:
```
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct  5 2017, 07:26:46) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytraj as pt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pytraj/__init__.py", line 24, in <module>
    from .utils.misc import info
  File "pytraj/utils/misc.py", line 7, in <module>
    from pytraj.core.c_options import set_world_silent
  File "pytraj/core/__init__.py", line 2, in <module>
    from .topology_objects import Atom, Residue, Molecule
ImportError: No module named topology_objects
```
However, I can see a bunch of topology_objects things in the pytraj directory in PYTHONPATH:
```
$ find $PYTHONPATH/pytraj-2.0.3.dev0-py2.7-linux-x86_64.egg/pytraj -name "topology_objects*"
/u/droe/.local/lib/python2.7/site-packages/pytraj-2.0.3.dev0-py2.7-linux-x86_64.egg/pytraj/core/topology_objects.pxd
/u/droe/.local/lib/python2.7/site-packages/pytraj-2.0.3.dev0-py2.7-linux-x86_64.egg/pytraj/core/topology_objects.py
/u/droe/.local/lib/python2.7/site-packages/pytraj-2.0.3.dev0-py2.7-linux-x86_64.egg/pytraj/core/topology_objects.pyc
/u/droe/.local/lib/python2.7/site-packages/pytraj-2.0.3.dev0-py2.7-linux-x86_64.egg/pytraj/core/topology_objects.so
```
Any idea what I've done wrong? Is this somehow related to the fact that I'm using anaconda?

**Comment by hainm** [comment] 2018-03-16 13:10
Did you import in source cod folder (where pytraj folder is)?

**Comment by drroe** [comment] 2018-03-16 13:30
> Did you import in source cod folder (where pytraj folder is)?

Ha! I knew it was something stupid I was doing. That was the problem.

However, I cannot reproduce your issue. Since cpptraj isn't linking to gfortran, I suspect that your BLAS and LAPACK are. If I look on my machine I see that my libcpptraj.so has gfortran even though there is no `-lgfortran` on the link line:
```
g++ -shared -o "/u/droe/GitHub/cpptraj/lib"/libcpptraj.so ActionFrameCounter.o ... pub_fft.o -llapack -lblas -L/v/apps/netcdf3/4.4.1.1/gcc_6.3.0/lib -lnetcdf -lbz2 -lz xdrfile/libxdrfile.a  -fopenmp
```
```
$ ldd lib/libcpptraj.so 
	linux-vdso.so.1 =>  (0x00007ffd203b7000)
	liblapack.so.3 => /lib64/liblapack.so.3 (0x00007f8769e87000)
	libblas.so.3 => /lib64/libblas.so.3 (0x00007f8769c2d000)
	libnetcdf.so.11 => /v/apps/netcdf3/4.4.1.1/gcc_6.3.0/lib/libnetcdf.so.11 (0x00007f876991b000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f876970b000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f87694f4000)
	libstdc++.so.6 => /v/apps/gcc/6.3.0-centos7/lib64/libstdc++.so.6 (0x00007f8769173000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f8768e71000)
	libgomp.so.1 => /v/apps/gcc/6.3.0-centos7/lib64/libgomp.so.1 (0x00007f8768c43000)
	libgcc_s.so.1 => /v/apps/gcc/6.3.0-centos7/lib64/libgcc_s.so.1 (0x00007f8768a2c000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f8768810000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f876844c000)
	libgfortran.so.3 => /v/apps/gcc/6.3.0-centos7/lib64/libgfortran.so.3 (0x00007f8768126000)
	/lib64/ld-linux-x86-64.so.2 (0x00005565200ac000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f8767f21000)
	libquadmath.so.0 => /v/apps/gcc/6.3.0-centos7/lib/../lib64/libquadmath.so.0 (0x00007f8767ce2000)
```
Looking further, I can see that it's BLAS (and LAPACK, not shown) that requires libgfortran:
```
$ ldd /lib64/libblas.so
	linux-vdso.so.1 =>  (0x00007ffd77b58000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fb10c45d000)
	libgfortran.so.3 => /v/apps/gcc/6.3.0-centos7/lib64/libgfortran.so.3 (0x00007fb10c136000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fb10bd73000)
	/lib64/ld-linux-x86-64.so.2 (0x000055a12a4ff000)
	libquadmath.so.0 => /v/apps/gcc/6.3.0-centos7/lib/../lib64/libquadmath.so.0 (0x00007fb10bb34000)
	libgcc_s.so.1 => /v/apps/gcc/6.3.0-centos7/lib/../lib64/libgcc_s.so.1 (0x00007fb10b91c000)
(pytraj_test) [droe@tesla3 cpptraj] (master)$ ldd /lib64/liblapack.so
	linux-vdso.so.1 =>  (0x00007ffdc3fa6000)
	libblas.so.3 => /lib64/libblas.so.3 (0x00007f404e12b000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f404de28000)
	libgfortran.so.3 => /v/apps/gcc/6.3.0-centos7/lib64/libgfortran.so.3 (0x00007f404db02000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f404d73f000)
	/lib64/ld-linux-x86-64.so.2 (0x000055b2a3584000)
	libquadmath.so.0 => /v/apps/gcc/6.3.0-centos7/lib/../lib64/libquadmath.so.0 (0x00007f404d4ff000)
	libgcc_s.so.1 => /v/apps/gcc/6.3.0-centos7/lib/../lib64/libgcc_s.so.1 (0x00007f404d2e8000)
```
So I suspect that maybe what is happening on your setup is that libgfortran is being pulled in by your math libraries, but for some reason your system can't find it. Looking through your log it looks like you have 2 different versions of libgfortran being pulled in:
```
libgfortran-4.8-dev libgfortran3
```
Maybe this is causing some issues?

**Comment by hainm** [comment] 2018-03-17 06:06
> However, I cannot reproduce your issue. 

yeah, I can not reproduce this issue in my computer with the docker image. And I agree that there is something going on with linking to the libgfortran.

I don't know if this is coincident, but pytraj errors happened right after you had a fix for libgfortran on macos. I have not updated pytraj for a while.

# pytraj

<img width="941" alt="screen shot 2018-03-17 at 2 00 03 am" src="https://user-images.githubusercontent.com/4451957/37552236-853f9bdc-2987-11e8-94ae-aa1c79f5a762.png">

# cpptraj

<img width="990" alt="screen shot 2018-03-17 at 2 05 38 am" src="https://user-images.githubusercontent.com/4451957/37552243-b975f450-2987-11e8-8b22-c27c8455d243.png">

**Comment by hainm** [comment] 2018-03-17 06:07
I will do further digging.

**Comment by hainm** [comment] 2018-03-18 21:21
uhm, so I removed all the gfotran 5 and 6, and keep only gfortran 4.5

Here is the libcpptraj.so linking
```
ldd cpptraj/lib/libcpptraj.so
	linux-vdso.so.1 =>  (0x00007ffc6e9c5000)
	libnetcdf.so.7 => /usr/lib/libnetcdf.so.7 (0x00007fb7bb7a0000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007fb7bb590000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb7bb377000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb7bb064000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb7bad5e000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fb7bab2f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb7ba919000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb7ba6fb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb7ba332000)
	libhdf5_hl.so.7 => /usr/lib/x86_64-linux-gnu/libhdf5_hl.so.7 (0x00007fb7ba102000)
	libhdf5.so.7 => /usr/lib/x86_64-linux-gnu/libhdf5.so.7 (0x00007fb7b9c66000)
	libcurl-gnutls.so.4 => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007fb7b9a04000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb7bc1df000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb7b9800000)
	libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007fb7b95cd000)
	librtmp.so.0 => /usr/lib/x86_64-linux-gnu/librtmp.so.0 (0x00007fb7b93b3000)
	libgcrypt.so.11 => /lib/x86_64-linux-gnu/libgcrypt.so.11 (0x00007fb7b9133000)
	libgnutls.so.26 => /usr/lib/x86_64-linux-gnu/libgnutls.so.26 (0x00007fb7b8e74000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007fb7b8c2d000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007fb7b8a1e000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007fb7b87cd000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fb7b85c8000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007fb7b83b4000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007fb7b8172000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007fb7b7ea7000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007fb7b7c78000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007fb7b7a74000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007fb7b7869000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fb7b764e000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007fb7b7433000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007fb7b71f5000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fb7b6fed000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007fb7b6de9000)
	libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007fb7b6be0000)
	libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007fb7b6958000)
	libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007fb7b66b7000)
	libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007fb7b6484000)
	libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007fb7b626f000)
	libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007fb7b6046000)
	libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007fb7b5e38000)
	libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007fb7b5bef000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007fb7b5936000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fb7b56fd000)
```

Note: there is no `libblas.so` in this case.

Full log is here: 
[log_pytraj.txt](https://github.com/Amber-MD/cpptraj/files/1823140/log_pytraj.txt)

**Comment by hainm** [comment] 2018-03-18 21:30
So I've done my search, http://icl.cs.utk.edu/lapack-forum/viewtopic.php?f=4&t=2957, suggesting that `-lgfortran` is still needed.


I've check the pytraj build 7 days ago (WORKING) and see the last line in cpptraj log
`
[PLACE HOLDER] ReadLine.LIBCPPTRAJ.o pub_fft.o -L/usr/local//lib -llapack -L/usr/local//lib -lblas -lgfortran -lnetcdf -L/home/travis/miniconda3/envs/myenv/lib -lbz2 -L/home/travis/miniconda3/envs/myenv/lib -lz xdrfile/libxdrfile.a  -fopenmp 
`

cpptraj master (NOT-WORKING)
`
[PLACE HOLDER] ReadLine.LIBCPPTRAJ.o pub_fft.o -L/usr/local//lib -llapack -L/usr/local//lib -lblas -lnetcdf -L/home/travis/miniconda3/envs/myenv/lib -lbz2 -L/home/travis/miniconda3/envs/myenv/lib -lz xdrfile/libxdrfile.a  -fopenmp 
`

**Comment by drroe** [comment] 2018-03-19 12:44
> So I've done my search, http://icl.cs.utk.edu/lapack-forum/viewtopic.php?f=4&t=2957, suggesting that -lgfortran is still needed.

I don't understand this because CPPTRAJ's configure specifically checks whether `-lgfortran` is required for compiling with BLAS/LAPACK - see [here](https://github.com/Amber-MD/cpptraj/blob/3057062cb8b48c7f2c6c25cee9be121f3cdc858b/configure#L398-L439). So if your BLAS/LAPACK requires `-lgfortran`, that code should detect it. The fact that it isn't means that either there is another library that requires libgfortran, or somehow the linker is pulling in a different BLAS/LAPACK (maybe from AmberTools?).

In order to debug this further I'm going to have to reproduce it on a system where I can work interactively. I haven't been able to thus far. Can you come up with an environment where this is a problem (i.e. not on a CI platform)? I'll keep trying to reproduce in the meantime.

Note that the temporary workaround here is to pass `--requires-flink` to `configure`.

**Comment by hainm** [comment] 2018-03-19 14:42
Thanks Dan. I will try to make the temporary workaround like you suggested.
This's not urgent issue since it only happens on travis (like I said
before, I could not reproduce the issue myself :D).
Just leave this issue open for now. thanks.

**Closed** 2019-02-25 23:52 UTC
